settings:
  clientid: 'GoMySysBootloader'
  broker: "tcp://test.mosquitto.org:1883"
  subtopic: 'mysensors_rx'
  pubtopic: 'mysensors_tx'

control:
    nextid: 12
    firmwarebasepath: '../test_files'
    nodes:
        default: { type: 1, version: 1 }
        1: { type: 1, version: 1 }
